username = 'YOUR_REDDIT_ACCOUNT_USERNAME'
password = 'YOUR_REDDIT_ACCOUNT_PASSWORD'
client_id = 'CAN_BE_FOUND_IN_REDDIT_PREFERENCES_UNDER_THE_HEADING_"APPS"'
client_secret = 'CAN_BE_FOUND_IN_REDDIT_PREFERENCES_UNDER_THE_HEADING_"APPS"'
